import requests
import os
import urllib3

# Suppress InsecureRequestWarning since we are explicitly disabling SSL verify
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

class ClickUpManager:
    def __init__(self):
        self.api_token = os.getenv('CLICKUP_API_TOKEN')
        self.list_id = os.getenv('CLICKUP_LIST_ID')
        self.base_url = "https://api.clickup.com/api/v2"
        self.headers = {
            "Authorization": self.api_token,
            "Content-Type": "application/json"
        }
        # Disable SSL verification to handle corporate firewalls
        self.verify_ssl = False

    def _get_custom_fields(self):
        """Fetch custom fields for the list to map names to IDs."""
        if not self.api_token or not self.list_id:
            return {}
        
        url = f"{self.base_url}/list/{self.list_id}/field"
        try:
            response = requests.get(url, headers=self.headers, verify=self.verify_ssl)
            if response.status_code == 200:
                fields = response.json().get('fields', [])
                return {f['name'].lower(): f['id'] for f in fields}
            return {}
        except Exception as e:
            print(f"Error fetching custom fields: {e}")
            return {}

    def create_or_update_task(self, ticker, data):
        """
        Creates a task for the ticker or updates it if it exists.
        """
        if not self.api_token or not self.list_id:
            return {"error": "ClickUp credentials not configured (CLICKUP_API_TOKEN, CLICKUP_LIST_ID)"}

        # 1. Check if task exists
        task_id = None
        try:
            url = f"{self.base_url}/list/{self.list_id}/task?archived=false"
            response = requests.get(url, headers=self.headers, verify=self.verify_ssl)
            if response.status_code == 200:
                tasks = response.json().get('tasks', [])
                for task in tasks:
                    if task['name'].upper() == ticker.upper():
                        task_id = task['id']
                        break
        except Exception as e:
            print(f"Error searching tasks: {e}")

        # 2. Prepare Custom Fields
        field_map = self._get_custom_fields()
        custom_fields = []
        
        def add_field(name, value):
            fid = field_map.get(name.lower())
            if fid:
                custom_fields.append({"id": fid, "value": value})

        add_field("Current Price", data.get('price'))
        add_field("Sentiment Score", data.get('sentiment_score'))
        add_field("News Summary", data.get('summary'))
        add_field("Buy/Sell Flag", data.get('recommendation'))

        # 3. Create or Update
        payload = {
            "name": ticker.upper(),
            "description": f"AI Analysis for {ticker}.\n\nSummary: {data.get('summary')}\n\nGenerated by AI Agent.",
            "custom_fields": custom_fields,
        }

        try:
            if task_id:
                # Update
                url = f"{self.base_url}/task/{task_id}"
                response = requests.put(url, headers=self.headers, json=payload, verify=self.verify_ssl)
                action = "updated"
            else:
                # Create
                url = f"{self.base_url}/list/{self.list_id}/task"
                response = requests.post(url, headers=self.headers, json=payload, verify=self.verify_ssl)
                action = "created"

            if response.status_code in [200, 201]:
                return {"success": True, "action": action, "task": response.json()}
            else:
                return {"error": f"ClickUp API Error: {response.text}"}

        except Exception as e:
            return {"error": str(e)}
