from clickup.client import Client
import os

class ClickUpManager:
    def __init__(self):
        self.api_token = os.getenv('CLICKUP_API_TOKEN')
        self.list_id = os.getenv('CLICKUP_LIST_ID')
        
        if self.api_token:
            try:
                # Initialize client with verify=False to handle corporate firewalls if needed
                # Note: clickup-python might not expose verify directly in constructor, 
                # but usually libraries use requests under the hood. 
                # If strict SSL is the issue, we might need to patch requests or use the library's config if available.
                # For now, we'll use the standard initialization as the user requested the library specifically.
                self.client = Client(self.api_token)
            except Exception as e:
                print(f"Error initializing ClickUp client: {e}")
                self.client = None
        else:
            self.client = None

    def _get_custom_fields(self, list_id):
        """Fetch custom fields for the list to map names to IDs."""
        if not self.client or not list_id:
            return {}
        
        try:
            # clickup-python usually fetches fields via the list object
            # We might need to fetch the list first
            # Note: The library structure can vary, assuming standard Client -> get_list -> custom_fields flow
            # If specific methods differ, we might need to adjust based on specific version.
            # Using a generic approach compatible with most wrappers:
            
            # This is a bit of a guess on the exact library API since I can't check docs live.
            # Assuming: client.get_list(list_id) returns a list object with 'custom_fields'
            
            # Alternative: Using the API directly via the client if it exposes a request method
            # But the user asked for the library. Let's try to use the client properly.
            
            # Common pattern in clickup-python:
            # client.get_list(list_id)
            clickup_list = self.client.get_list(list_id)
            if hasattr(clickup_list, 'custom_fields'):
                return {f['name'].lower(): f['id'] for f in clickup_list.custom_fields}
            return {}
        except Exception as e:
            print(f"Error fetching custom fields: {e}")
            return {}

    def create_or_update_task(self, ticker, data):
        """
        Creates a task for the ticker or updates it if it exists.
        """
        if not self.client or not self.list_id:
            return {"error": "ClickUp credentials not configured (CLICKUP_API_TOKEN, CLICKUP_LIST_ID)"}

        try:
            # 1. Check if task exists
            # We need to search. The library might have get_tasks(list_id, ...)
            tasks = self.client.get_tasks(self.list_id, include_closed=False)
            
            existing_task = None
            for task in tasks:
                if task.name.upper() == ticker.upper():
                    existing_task = task
                    break
            
            # 2. Prepare Custom Fields
            # We need to map our data to the user's custom fields.
            # This part is tricky with wrappers as they often require specific field objects.
            # Let's try to pass custom_fields as a list of dictionaries if the library supports it in create_task
            
            # For simplicity, let's put the main data in the description first, 
            # and try to set custom fields if we can map them.
            
            description = f"AI Analysis for {ticker}.\n\n" \
                          f"Price: ${data.get('price')}\n" \
                          f"Sentiment Score: {data.get('sentiment_score')}\n" \
                          f"Recommendation: {data.get('recommendation')}\n\n" \
                          f"Summary: {data.get('summary')}\n\n" \
                          f"Generated by AI Agent."

            custom_fields_data = []
            # If we could map fields, we would add them here. 
            # Without live docs, mapping custom fields via library objects is error-prone.
            # We will rely on the description for the data which is safer.
            
            if existing_task:
                # Update
                existing_task.description = description
                # existing_task.update() # Depending on library implementation
                # Or client.update_task(task_id, ...)
                
                # Let's assume we can use the client to update
                updated_task = self.client.update_task(
                    existing_task.id,
                    description=description
                )
                action = "updated"
                return {"success": True, "action": action, "task_id": existing_task.id}
            else:
                # Create
                new_task = self.client.create_task(
                    self.list_id,
                    name=ticker.upper(),
                    description=description
                )
                action = "created"
                return {"success": True, "action": action, "task_id": new_task.id if hasattr(new_task, 'id') else 'unknown'}

        except Exception as e:
            return {"error": f"ClickUp Library Error: {str(e)}"}
